# Generated by Django 3.1 on 2020-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200812_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
